name: clang-format

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DoozyX/clang-format-lint-action@v0.16.2
      name: clang-format
      with:
        source: '.'
        extensions: 'hpp,h,cpp,c'
        clangFormatVersion: 16    
